name: auto-release

on:
  push:

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get Repo main branch name
        run: |
          DEFAULT_BRANCH=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }} | jq -r '.default_branch')
          echo "DEFAULT_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV
          echo "DEFAULT_BRANCH: ${DEFAULT_BRANCH}"

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install frontend dependencies
        run: bun install

      - name: Parse ChangeLog and Set Version
        run: |
          npm run parseChangeLog

      - name: Display next version
        run: |
          echo "next_version: ${next_version}"

      - name: Update Package Version
        run: |
          npm version ${next_version} --no-git-tag-version

      - name: Commit and Push
        run: |
          git config --global user.name 'Alex-Programmer-Bro'
          git config --global user.email 'alex.lichangnan@gmail.com'
          git add package.json
          git commit -m "Update package version"
          git push https://${{ secrets.G_TOKEN }}@github.com/${{ github.repository }} HEAD:${DEFAULT_BRANCH} --force
