name: "Unit and E2E Test"

on:
  pull_request:
    branches:
      - 'v*'

jobs:
  Test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install frontend dependencies
        run: bun install
        
      - name: Unit Test
        run: npm run test:unit

      - name: Install Playwright
        run: npx playwright install chromium

      - name: E2E Test
        run: npm run test:e2e
