name: "UI Tests"

on: push

jobs:
  Test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11

      - name: install frontend dependencies
        run: bun install

      - name: Unit Test
        run: npm run test:unit

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: unit and e2e
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npm run storybook" \
            "npx wait-on tcp:6006 && npm run test:e2e"
