name: "UI Tests"

on: push

jobs:
  interaction-and-accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install frontend dependencies
        run: bun install

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Build Storybook
        run: yarn build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && yarn test-storybook"
